### ISSUE TITLE
Docs: `h` and `w` arguemnt names are called "column" and "row" in the documentation

### ISSUE THREAD

**Issue by daattali** [petergandenberger/gridstackeR#10]
`h` and `w` obviously stand for height and width, but the function documentation for these parameters mentions column/row. I see that this is also the text used in the gridstackjs documentation, so I assume it was just copied from there :) But I think it would be nicer to be consistent and more clear.

**Comment by petergandenberger** [comment]
What do you suggest I change it to?
Currently it states `@param w,h element size in columns/rows`, i.e how many columns/rows should the element be wide/high.
This is in reference to `@param ncols number of columns for the grid` from the surrounding grid.

**Comment by daattali** [comment]
The choice is less important, consistency is more important. If you go with `h`/`w` then the corresponding documentation should use language with words like "height" and "width". And for `x`/`y` parameters, since the documentation says this is position in rows/columns, then perhaps using `col`/`row` paramter names will be clearer for users.

**Comment by petergandenberger** [comment]
Done as you suggested in #19 with 009aded
