### ISSUE TITLE
Is grid_stack() meant to ONLY contain grid_stack_item()?

### ISSUE THREAD

**Issue by daattali** [petergandenberger/gridstackeR#14]
If yes, then the documentation doesn't make that clear. The argument `...` currently says "content to include in the container", it should clarify that only `grid_stack_item()` are allowed. And ideally there will be error checking with an informative error if a wrong item is provided.

If no, then I just haven't figured out how it makes sense to place other items there :)

**Comment by petergandenberger** [comment]
The `...` keeps it open to e.g. adding `style = 'background: blue;'` if anyone wants that.
But I can't think of another use-case except for _style_, so I will change it and people have to style using non-inline css.

**Comment by daattali** [comment]
If you, as the author, can't think of any HTML elements that can be added and can't provide a single example, it might be better to not claim that it's open-ended. Can it be used for adding **any** attributes? Can I add a class or any other attributes? If yes, then docs can say this is used for adding attributes specifically.
