### ISSUE TITLE
grid_stack_item: Height/width in the parameter is treated as number of columns/rows (with a base 12); but is returned as pixels

### ISSUE THREAD

**Issue by daattali** [petergandenberger/gridstackeR#19]
When creating a grid item, I can provide `h` and `w` as numbers. For example `w=6` would result in an item taking up half the width, and `h=6` would make it have the same height. But when the value for height and width are returned as an input, these values are provided as pixels. This is perhaps useful for some usecases, but it also creates an inconsistency and it means that I can't re-create a grid easily.

I can see by looking at the DOM that there are HTML attributes on the item `gs-x` `gs-y` `gs-h` `gs-w`, it would make sense to simply return those.

This is related to #10 - the distinction between columns/rows and height/width is important because it makes it clear what the units should be. When I see "rows/columns" I assume it's using the 12-row grid as the basis for units. When I see "height/width" then pixels can make sense.

**Comment by petergandenberger** [comment]
Done as you suggested in 009aded
