### ISSUE TITLE
grid_stack_item(overflow)

### ISSUE THREAD

**Issue by daattali** [petergandenberger/gridstackeR#5]
It looks like a lot of example usages of `grid_stack_item()` add a `style = "overflow:hidden"`. Is the only purpose so that while you're in the process of resizing, there won't be a scrollbar?
If you think it's very useful and you often use it, it may be a good idea to either include it automatically or have an explicit parameter for it that would achieve the same effect by default.

**Comment by petergandenberger** [comment]
The reason for `style = "overflow:hidden"` is to prevent the content to overflow in case the content is larger than the `grid_stack_item()` (e.g. a `shinydashboard::box` might contain a plot that is larger than the `grid_stack_item()`, this would destroy the whole idea of resizing)

But I like your idea of adding it as a default with a parameter to disable it inside of the `grid_stack_item()`
