### ISSUE TITLE
Usage of shinyjs::extendShinyjs(text) vs extendShinyjs(script)

### ISSUE THREAD

**Issue by daattali** [petergandenberger/gridstackeR#6]
I noticed that there are several consecutive calls to `shinyjs::extendShinyjs()` that are all using the `text` parameter  https://github.com/petergandenberger/gridstackeR/blob/36a2202a9ad615db3ef9ca74432222b49faabffa/R/gridstackeR.R#L127-L133

I'm curious if there's a good reason not to place all these functions in a JavaScript file and import them all together? I'm asking since I'm the author of {shinyjs} and I would like to know if there was any issue with it

**Comment by petergandenberger** [comment]
Done :)
